name: Feature request
description: Suggest an improvement.
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Explain the user problem and desired behavior.
    validations:
      required: true
